### ISSUE TITLE
IPG Implementation guide for the new iDEAL transactions

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-ems-e-commerce#4]
_Source: https://www.emspay.com/nl/en/support/implementation-guide-ideal-ipg_

> This document explains the changes required to be made by EMS merchants to process the new iDEAL transactions as per 1 July 2024.
> 
> EMS merchants need to change the checkout option to 'combined page’
> 
> For a standard hosted payment page integration, you should use the checkout option ‘combinedpage’ that consolidates the payment method choice and the typical next step (e.g.: entry of card details or selection of bank) in a single page, which gets automatically optimized for different kinds of user devices (e.g.: PC, smartphone, tablet, etc.).
> 
> Merchant have to change the field ‘checkoutoption’ from ‘classic’ for a payment process that is split into multiple pages to ‘combinedpage’ for a payment process where the payment method choice and the typical next step (e.g. entry of card details or selection of bank) in consolidated in a single page to continue submitting iDEAL sales.
> 
> Change needed in the integration used by EMS merchant to change checkout option (if they are on classic option).
> 
> 
> Below example demonstrates a simple page that will communicate with the payment gateway.
> 
> When the cardholder clicks Submit, they are redirected to the secure page to enter the card details. After payment has been completed, the user will be redirected to the merchant’s receipt page. The location of the receipt page can be configured.
> 
> 
> Code snippet where the change needs to be made
> 
> 
> Screenshot of checkout page
> 
> URL for Test Transactions
> 
> [https://test.ipg-online.com/connect/gateway/processing](file:///C:/Users/PVDBOO~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml)
> 
> When building a request, independently of the payment method, there are some mandatory fields that need to be included in every request for a Sale transaction.
> 
> Example of a form with the minimum number of fields:
> 
> 
> Please be aware third party Plugins are not in control of EMS. So it could be different for your plugin on where to make the adjustment. Please contact your Plugin developer to validate where the adjustment need to be done to go from checkoutoption Classic to Combinedpage.

We don't use the `checkoutoption` parameter, no action required @rvdsteege?

_Via https://wordpress.org/support/topic/ideal-2-0/#post-17761778_

**Comment by rvdsteege** [comment]
I already enquired with EMS about that, but unfortunately, I have not received a reply in the past month (I'm not sure if it has been received/read):
- https://secure.helpscout.net/conversation/2572360049/27132

**Comment by rvdsteege** [comment]
Discussed with @remcotolsma at office and decided to add the `checkoutoption=combinedpage` parameter, just in case.
